Fix for NoMethodError: undefined method `supports_value_expectations?'
With [this change](https://github.com/rspec/rspec-expectations/pull/1139) in rspec-expectations, a call to `expect(my_object).to have(...)` is raising a `NoMethodError: undefined method `supports_value_expectations?' for <MyObject:0x000055a1b6e065c0>`. 

This is because ExpectationTarget calls `supports_value_expectation` here:

https://github.com/rspec/rspec-expectations/blob/4e7011fe8ac68b74621336b07f894879c8da202d/lib/rspec/expectations/expectation_target.rb#L127

Which ends up being processed by `Have#method_missing` which sets `supports_value_expectations?` to @collection_name. Later in `Have#determine_collection` it tries to call `supports_value_expectations?` on my_object, which causes the NoMethodError.

The fix is simple, just implement `Have#supports_value_expectations?`.